//#include <random>
//#include <iostream>
//
//int main()
//{
//    std::random_device rd;  //Will be used to obtain a seed for the random number engine
//    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
//    std::uniform_int_distribution<> dis(1, 6);
//
//    for (int n=0; n<10; ++n)
//        //Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
//        std::cout << dis(gen) << ' ';
//    std::cout << '\n';
//}

#include <stdio.h>
#include <stdlib.h>
int a[100], count;
void comb(int m, int k)
{
    int i, j;
    for(i = m; i >= k; --i)
    {
        // 用来存储每个组合中的数据
        a[k] = i;
        if(k > 1)
            comb(i - 1, k - 1);
        else
        {
            for(j = a[0]; j > 0; --j)
                printf("%d ", a[j]);
            printf("\n");
            ++ count;
        }
    }
}
// 从n个数中选r个数的组合
int main()
{
    int n, r;
    count = 0;
    printf("Please input n and r:\n");
    scanf("%d %d", &n, &r);
    if(r > n)
        printf("input n, r  error!");
    else
    {
        // a[0]仅仅充当一个变量的作用
        a[0] = r;
        comb(n, r);
    }
    printf("Total numbers : %d", count);
    return 0;
}